# Generated by Django 4.2 on 2023-04-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("functionality", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="user_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="date_time_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
