# Generated by Django 4.2 on 2023-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("functionality", "0003_alter_activity_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
