# Generated by Django 4.2 on 2023-05-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("functionality", "0006_alter_activity_date_time_added"),
    ]

    operations = [
        migrations.RemoveField(model_name="activity", name="date_time_finish",),
    ]
