# Generated by Django 4.2 on 2023-05-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "functionality",
            "0008_remove_activity_completed_activity_completion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity", name="date_time_added", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="activity", name="date_time_start", field=models.DateField(),
        ),
        migrations.CreateModel(
            name="SubActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("booster", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "activity_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="functionality.activity",
                    ),
                ),
            ],
        ),
    ]
