# Generated by Django 4.2 on 2023-05-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("functionality", "0009_alter_activity_date_time_added_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="activity", name="date_time_added",),
    ]
